name: Build terraform

on:
  push:
     branches:
        -main
jobs:
   call-workflow-passing-data:
      uses: multi_branch_build/.github/workflows/runner.yml@main
      with:
         username: tri
