# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ Nightly ]
  pull_request:
    branches: [ Nightly ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    # Steps represent a sequence of tasks that will be executed as part of the job
      uses: actions/checkout@v2
    steps: 
      - name: Parse test input file
        id: set-matrix
        run: | 
           file_content=`cat ${{ github.workspace }}/.github/workflows/sample.json | jq ".builds.nightly.tests" | tr -d '\n'`
           echo "Prepare matrix with: $file_content"
           echo "::set-output name=matrix::{\"tests\":$file_content}"
  test:
    env:
       test-stat: start
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJSON(needs.build.outputs.matrix)}} 
    outputs:
      mtx-status: ${{ steps.mtx.outputs.mtx_status }}
    steps:
      - name: Run matrix
        uses: actions/download-artifact@v2
        with:
           name: build-fail
        continue-on-error: true
      - name: Run matrixi
        id: mtx
        run:  |
            echo "Excuting ${{matrix.node }}"
            sleep 10
            if [ -f "previous_test_failed.txt" ]; then
                cat previous_test_failed.txt
                exit 1
            fi
            if [ ! -f "previous_test_failed.txt" ]; then 
                echo "Start ${{matrix.tests }}"
                echo "LOAD TERRAFORM"
            fi
            if [ ${{matrix.tests}} == "test2" ] ; then
                ls junk
            fi
      - if: ${{ failure() }}
        run:  | 
           touch previous_test_failed
           echo "${{matrix.tests }} failed" >> ${{ runner.temp }}/previous_test_failed.txt
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
            name: build-fail
            path: ${{ runner.temp }}/
      
