# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Nightly branch
  push:
    branches: [ Nightly ]
  pull_request:
    branches: [ Nightly ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    # Steps represent a sequence of tasks that will be executed as part of the job
      uses: actions/checkout@v2
    steps: 
      - name: test1
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: set-matrix
        run: | 
           file_content=`cat ${{ github.workspace }}/.github/workflows/sample`
           echo "$file_content"
           echo "::set-output name=matrix::{\"node\":[$file_content]}"
  test:
    env:
       test-stat: start
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJSON(needs.build.outputs.matrix)}} 
    outputs:
      mtx-status: ${{ steps.mtx.outputs.mtx_status }}
    steps:
      - name: Run matrix
        id: mtx
        run:  |
            echo "Excuting ${{matrix.node }}"
            echo "S: ${{ env.test-stat }}"
            if [ ${{matrix.node}} == "test2" ] ; then
                ls junk
            fi
      - if: ${{ failure() }}
        run:  |
           touch ${{ runner.temp }}/build_log
           echo "${{matrix.node}} Failed" >> ${{ runner.temp }}/build_log
           echo "::set-output name=mtx_status::'failed'"
           echo '::set-env name=test-stat::stop'
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
            name: build-fail
            path: ${{ runner.temp }}/build_log
      
