name: Call a reusable workflow and use its outputs

on:
   pull_request:
    branches:
      - main
jobs:
  job1:
    uses: https://github.com/kenvin007/multi_branch_build/.github/workflows/test.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
